using GestaoDeEquipamentos.ConsoleApp.Compartilhado;
using GestaoDeEquipamentosConsoleApp1.Compartilhado;

namespace GestaoDeEquipamentos.ConsoleApp.ModuloFabricante;

public class RepositorioFabricante : RepositorioBase;